// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Bootstrap operator seed (AC-AUTH-005, plan.md §5.3 Step 3). Runs via
    // plain `node` — see prisma/seed.ts header comment for why it avoids
    // the project's `@/*` path alias and the generated Prisma client.
    seed: "node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
