// Inspot UI-kit sample data (mirrors prototype/src/mocks). Plain global — no modules.
window.INSPOT_DATA = {
  servers: [
    { id: 'srv-01', name: 'web-prod-01', status: 'running', cpuPct: 38, ramPct: 62, diskPct: 54, cpu: '4 vCPU', ram: '16 GB', disk: '160 GB NVMe', ip: '49.12.34.56', location: 'Nuremberg, DE', os: 'Ubuntu 24.04 LTS' },
    { id: 'srv-02', name: 'web-prod-02', status: 'running', cpuPct: 44, ramPct: 58, diskPct: 49, cpu: '4 vCPU', ram: '16 GB', disk: '160 GB NVMe', ip: '49.12.34.78', location: 'Falkenstein, DE', os: 'Ubuntu 24.04 LTS' },
    { id: 'srv-03', name: 'db-primary', status: 'running', cpuPct: 71, ramPct: 82, diskPct: 68, cpu: '8 vCPU', ram: '32 GB', disk: '320 GB NVMe', ip: '78.46.12.34', location: 'Nuremberg, DE', os: 'Debian 12' },
    { id: 'srv-04', name: 'db-replica', status: 'stopped', cpuPct: 0, ramPct: 0, diskPct: 61, cpu: '8 vCPU', ram: '32 GB', disk: '320 GB NVMe', ip: '78.46.12.56', location: 'Helsinki, FI', os: 'Debian 12' },
    { id: 'srv-05', name: 'cache-node', status: 'running', cpuPct: 22, ramPct: 88, diskPct: 34, cpu: '2 vCPU', ram: '8 GB', disk: '80 GB NVMe', ip: '116.203.45.67', location: 'Nuremberg, DE', os: 'Ubuntu 24.04 LTS' },
    { id: 'srv-06', name: 'dev-staging', status: 'stopped', cpuPct: 0, ramPct: 0, diskPct: 28, cpu: '2 vCPU', ram: '8 GB', disk: '80 GB NVMe', ip: '116.203.45.89', location: 'Falkenstein, DE', os: 'Ubuntu 24.04 LTS' },
  ],
  domains: [
    { id: 'dom-01', name: 'inspot.app', provider: 'Cloudflare', registrar: 'Cloudflare', health: 'good', label: 'Активен', days: 640 },
    { id: 'dom-02', name: 'inspot.io', provider: 'Cloudflare', registrar: 'Namecheap', health: 'good', label: 'Активен', days: 560 },
    { id: 'dom-03', name: 'inspot-cdn.net', provider: 'Hetzner', registrar: 'Hetzner', health: 'warning', label: '21д', days: 21 },
    { id: 'dom-04', name: 'staging.inspot.dev', provider: 'GoDaddy', registrar: 'GoDaddy', health: 'critical', label: 'Истёк', days: -3 },
  ],
  alerts: [
    { id: 'a1', severity: 'critical', title: 'Сервер web-prod-01 недоступен', source: 'web-prod-01', service: 'nginx', ago: '2м', ack: false },
    { id: 'a2', severity: 'critical', title: 'PostgreSQL: слишком много подключений', source: 'db-primary', service: 'postgresql', ago: '9м', ack: false },
    { id: 'a3', severity: 'warning', title: 'Redis: память 88% (5.3 / 6.0 GB)', source: 'cache-node', service: 'redis', ago: '13м', ack: false },
    { id: 'a4', severity: 'warning', title: 'Домен inspot-cdn.net истекает через 21 день', source: 'cloudflare', service: 'dns', ago: '1ч', ack: false },
  ],
  emails: [
    { id: 'e1', from: 'Hetzner Cloud', subject: 'Плановое обслуживание в Nuremberg DC', ago: '18м', read: false },
    { id: 'e2', from: 'Cloudflare', subject: 'SSL-сертификат для inspot.app продлён', ago: '1ч', read: false },
    { id: 'e3', from: 'GitHub', subject: '[inspot/api] Деплой #482 завершён успешно', ago: '3ч', read: true },
    { id: 'e4', from: 'Stripe', subject: 'Платёж получен — €49.00', ago: '5ч', read: true },
  ],
  logs: [
    { id: 'l1', ts: '10:23:45', level: 'critical', source: 'web-prod-01', service: 'nginx', message: 'upstream timed out (110: Connection timed out) while connecting to backend:3000', details: 'PID 28491 | Client: 185.220.101.34 | Request: GET /api/v2/analytics | Upstream: backend:3000 | Timeout: 60s | Retries: 3/3 exhausted' },
    { id: 'l2', ts: '10:22:18', level: 'error', source: 'db-primary', service: 'postgresql', message: 'connection to database "inspot_prod" failed: FATAL: too many connections (max 200)', details: 'PID: 31245 | Current connections: 200/200 | Client: 10.0.1.45 | Application: api-gateway' },
    { id: 'l3', ts: '10:21:00', level: 'warn', source: 'cache-node', service: 'redis', message: 'memory usage exceeded warning threshold: 85% (4.8GB / 6.0GB)', details: 'Used: 5153960755 bytes | Max: 6442450944 bytes | Eviction: allkeys-lru | Fragmentation: 1.12' },
    { id: 'l4', ts: '10:20:30', level: 'info', source: 'cloudflare', service: 'waf', message: 'WAF rule triggered: SQL Injection attempt blocked (rule 942100)', details: 'Zone: inspot.app | IP: 91.234.56.78 | Action: BLOCK | Country: RU' },
    { id: 'l5', ts: '10:19:45', level: 'info', source: 'web-prod-02', service: 'systemd', message: 'Started Daily apt download activities', details: 'Unit: apt-daily.service | Result: success' },
    { id: 'l6', ts: '10:18:12', level: 'debug', source: 'api-gateway', service: 'node', message: 'cache hit ratio 0.94 over last 5m window', details: 'hits: 18422 | misses: 1176 | keys: 3049' },
    { id: 'l7', ts: '10:17:03', level: 'warn', source: 'web-prod-01', service: 'nginx', message: 'client sent invalid Host header while reading client request', details: 'Client: 45.155.205.108 | Host: (empty) | Action: 400' },
    { id: 'l8', ts: '10:15:30', level: 'error', source: 'db-replica', service: 'postgresql', message: 'replication lag exceeded 30s (current: 47s)', details: 'Primary LSN: 3A/9F0012 | Replica LSN: 3A/9C0044 | Lag: 47s' },
  ],
  levels: {
    debug: { label: 'DEBUG', tone: 'neutral', icon: 'ri-bug-line' },
    info: { label: 'INFO', tone: 'accent', icon: 'ri-information-line' },
    warn: { label: 'WARN', tone: 'amber', icon: 'ri-alert-line' },
    error: { label: 'ERROR', tone: 'red', icon: 'ri-error-warning-line' },
    critical: { label: 'CRIT', tone: 'red', icon: 'ri-close-circle-line' },
  },
  nav: [
    { path: 'dashboard', label: 'Дашборд', icon: 'ri-home-line' },
    { path: 'servers', label: 'Серверы', icon: 'ri-server-line' },
    { path: 'domains', label: 'Домены', icon: 'ri-global-line' },
    { path: 'monitoring', label: 'Мониторинг', icon: 'ri-dashboard-line' },
    { path: 'backups', label: 'Бэкапы', icon: 'ri-hard-drive-3-line' },
    { path: 'mail', label: 'Почта', icon: 'ri-mail-line' },
    { path: 'logs', label: 'Логи', icon: 'ri-file-list-3-line' },
    { path: 'alerts', label: 'Оповещения', icon: 'ri-alert-line' },
  ],
};
